server:
  port: 8888
spring:
  datasource:
    name: dataSource
    url: jdbc:mysql://127.0.0.1:3306/answer?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: YouMe_Stark@@
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl